<a href="https://colab.research.google.com/github/AbhinavKumar07/C126/blob/main/C126.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [22]:
import numpy as np
import random

rewards = np.array([
    [-1,-1,-1,-1,0,-1],
    [-1,-1,-1,0,-1,100],
    [-1,-1,-1,0,-1,-1],
    [-1,0,0,-1,-1,-1],
    [0,-1,-1,-1,-1,100],
    [-1,-1,-1,-1,0,100]
])



In [23]:
def set_initial_state():
  return np.random.randint(0,6)

set_initial_state()

3

In [24]:
def get_action(current_state , reward_matrix):
  available_action = []
  print("Reward_matrix","\n" , reward_matrix)

  for action in enumerate(reward_matrix[current_state]):
    if action[1] != -1 :
      available_action.append(action[0])

  choose_action = random.choice(available_action)
  print("Random choice of action from" , available_action , "is" , choose_action)
  return choose_action

In [25]:
#current_state = 4
#action = get_action(current_state , rewards)
#print(action)

In [26]:
current_state = 5
action = get_action(current_state , rewards)
print(action)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4, 5] is 5
5


In [27]:
#current_state = 0
#action = get_action(current_state , rewards)
#print(action)

In [28]:
#current_state = 1
#action = get_action(current_state , rewards)
#print(action)

C125


In [29]:
q_matrix = np.zeros([6,6])
print(q_matrix)


[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]


In [30]:
gamma = 0.8
def take_action(current_state,reward_matrix,gamma):
  action = get_action(current_state,reward_matrix)
  current_reward = reward_matrix[current_state,action]
  print("Current reward:" , current_reward)

  q_value = max(q_matrix[action])
  print("q-value:" , q_value)

  q_current_state = current_reward + (gamma * q_value)
  print("Q-current-state",q_current_state)

  q_matrix[current_state,action] = q_current_state
  print("Q-matrix:" ,"\n" , q_matrix)

  new_state = action

  print("**********************************************************")

  if(new_state == 5):
    print("Reached goal")
  else:
    print(f"Old state:{current_state} New state: {new_state}")
  return new_state

take_action(current_state,rewards,gamma)

Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4, 5] is 4
Current reward: 0
q-value: 0.0
Q-current-state 0.0
Q-matrix: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
**********************************************************
Old state:5 New state: 4


4

In [32]:
#C126

def run_episode(initial_state , reward_matrix, gamma):
  new_state = take_action(initial_state , reward_matrix , gamma)
  while True:
    if(new_state == 5):
      break
    else:
      new_state = take_action(new_state,reward_matrix,gamma)
    print(new_state)


In [33]:
def train(episodes , reward_matrix , gamma):
  print("train:")
  for episode in range(episodes):

    print("Starting episode:"  , episode)
    initial_state = set_initial_state()
    print("Initial_state:" , initial_state)

    if(initial_state != 5 ):
      run_episode(initial_state , reward_matrix ,gamma)
    print("Ending episode:" , episode)

  print("Training completed")
  return q_matrix



In [34]:
gamma = 0.8
q_table = train(20,rewards, gamma)
print("Final q-table:\n" , q_table)

train:
Starting episode: 0
Initial_state: 0
Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [4] is 4
Current reward: 0
q-value: 0.0
Q-current-state 0.0
Q-matrix: 
 [[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
**********************************************************
Old state:0 New state: 4
Reward_matrix 
 [[ -1  -1  -1  -1   0  -1]
 [ -1  -1  -1   0  -1 100]
 [ -1  -1  -1   0  -1  -1]
 [ -1   0   0  -1  -1  -1]
 [  0  -1  -1  -1  -1 100]
 [ -1  -1  -1  -1   0 100]]
Random choice of action from [0, 5] is 5
Current reward: 100
q-value: 0.0
Q-current-state 100.0
Q-matrix: 
 [[  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0. 100.]
 [  0.   0.  

In [53]:
def optimal_path(q_table):
  path = []
  reward = []
  total_reward = 0
  initial_state = set_initial_state()
  print(initial_state)

  max_value_index = np.argmax(q_table[initial_state])
  max_value = np.max(q_table[initial_state])
  path.append(max_value_index)
  reward.append(max_value)
  while max_value_index != 5:
    max_value_index = np.argmax(q_table[max_value_index])
    max_value = np.argmax(q_table[max_value_index])

    path.append(max_value_index)
    reward.append(max_value)

  total_reward = sum(reward)

  return path, total_reward

q_optimal_path , max_reward = optimal_path(q_table)

print(q_optimal_path , max_reward)

1
[5] 100.0
